export { api, SERVER_ORIGIN } from './axios'
export { authApi } from './auth'
export { matriculasApi } from './matriculas'
export { usuariosApi } from './usuarios'
export { catalogosApi } from './catalogos'
export { periodosApi } from './periodos'
export { docentesApi } from './docentes'
export { estudiantesApi } from './estudiantes'
export { actasApi } from './actas'
export type { FiltroActas } from './actas'
export { indicadoresApi } from './indicadores'
export type { FiltroIndicadores } from './indicadores'
export type { LoginResponse } from './auth'
export type { SolicitudMatriculaPayload, FiltroMatriculas, MiMatricula } from './matriculas'
export type { FacultadPayload, EspecialidadPayload } from './catalogos'
